### ISSUE TITLE
Addon doesn't work any longer.

### ISSUE THREAD

**Issue by localhosthack0r** [hubsif/kodi-tk_bbl#8]
Playback is broken, here a log snippet:

andre@yavdr06:~$ tail -f /var/lib/vdr/.kodi/temp/kodi.log 
                                                browser.submit()
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/resources/lib/mechanize/_mechanize.py", line 541, in submit
                                                return self.open(self.click(_args, *_kwds))
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/resources/lib/mechanize/_mechanize.py", line 203, in open
                                                return self._mech_open(url, data, timeout=timeout)
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/resources/lib/mechanize/_mechanize.py", line 255, in _mech_open
                                                raise response
                                            httperror_seek_wrapper: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
18:48:12 T:140020775516224   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tk_bbl/?scheduled_start=2016-09-23+18%3A45%3A00&mode=4&id=4695]
18:50:32 T:140019675158272   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'mechanize._response.httperror_seek_wrapper'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/default.py", line 195, in <module>
                                                browser.submit()
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/resources/lib/mechanize/_mechanize.py", line 541, in submit
                                                return self.open(self.click(_args, *_kwds))
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/resources/lib/mechanize/_mechanize.py", line 203, in open
                                                return self._mech_open(url, data, timeout=timeout)
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/resources/lib/mechanize/_mechanize.py", line 255, in _mech_open
                                                raise response
                                            httperror_seek_wrapper: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
18:50:32 T:140020775516224   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tk_bbl/?scheduled_start=2016-09-23+18%3A45%3A00&mode=4&id=4695]
18:50:42 T:140019658372864   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'mechanize._response.httperror_seek_wrapper'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/default.py", line 195, in <module>
                                                browser.submit()
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/resources/lib/mechanize/_mechanize.py", line 541, in submit
                                                return self.open(self.click(_args, *_kwds))
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/resources/lib/mechanize/_mechanize.py", line 203, in open
                                                return self._mech_open(url, data, timeout=timeout)
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/resources/lib/mechanize/_mechanize.py", line 255, in _mech_open
                                                raise response
                                            httperror_seek_wrapper: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
18:50:42 T:140020775516224   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tk_bbl/?scheduled_start=2016-09-23+18%3A45%3A00&mode=4&id=4697]
18:51:01 T:140019242997504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'mechanize._response.httperror_seek_wrapper'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/default.py", line 195, in <module>
                                                browser.submit()
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/resources/lib/mechanize/_mechanize.py", line 541, in submit
                                                return self.open(self.click(_args, *_kwds))
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/resources/lib/mechanize/_mechanize.py", line 203, in open
                                                return self._mech_open(url, data, timeout=timeout)
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/resources/lib/mechanize/_mechanize.py", line 255, in _mech_open
                                                raise response
                                            httperror_seek_wrapper: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
18:51:01 T:140020775516224   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tk_bbl/?scheduled_start=2016-09-30+18%3A45%3A00&mode=4&id=4677]
^C

**Comment by hubsif** [comment]
Thank you for your feedback.
This has been fixed with release v1.1.2.

**Comment by localhosthack0r** [comment]
Thank you so much, for your quick response and the update!
Installed the new Zip --> works. :+1:
