### ISSUE TITLE
Addon doesn't start

### ISSUE THREAD

**Issue by localhosthack0r** [hubsif/kodi-tk_bbl#9]
Seems that the Telekom changed something again,... :-(

Log:
20:11:36 T:140174713419520   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('children',)
                                            Traceback (most recent call last):
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/default.py", line 89, in <module>
                                                live_target = get_current(jsonResult)
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/default.py", line 50, in get_current
                                                result = get_current(child)
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/default.py", line 50, in get_current
                                                result = get_current(child)
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/default.py", line 50, in get_current
                                                result = get_current(child)
                                              File "/var/lib/vdr/.kodi/addons/plugin.video.tk_bbl/default.py", line 48, in get_current
                                                if json['children']:
                                            KeyError: ('children',)
                                            -->End of Python script error report<--
20:11:36 T:140176023959616   ERROR: GetDirectory - Error getting plugin://plugin.video.tk_bbl/
20:11:36 T:140176023959616   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tk_bbl/) failed

Thank you again, in advance, for your great work! :-)

**Comment by localhosthack0r** [comment]
BTW: There is thread about your addon at schoenen-dunk community. People report their findings in it:

http://www.schoenen-dunk.de/forum_t95470_Telekom-Basketball-fuer-XBMC-Kodi.htm

**Comment by localhosthack0r** [comment]
Wow, what a quick response!
Thank you very much, works for me. :D
